[package]
name = "servo-gtk"
version = "0.1.0"
edition = "2024"

[lib]
name = "servo_gtk"
path = "servo_gtk/lib.rs"

[[example]]
name = "browser"
path = "examples/browser.rs"

[dependencies]
gio = "0.22"
glib = { version = "0.22", features = ["v2_74", "log_macros"] }
gtk = { package="gtk4", version="0.11", features=["v4_10"] }
servo = { git = "https://github.com/servo/servo.git", rev = "e8dbc1dfbf6f58621346a5f61ab7a17d01387873" }
servo-embedder-traits = { git = "https://github.com/servo/servo.git", rev = "e8dbc1dfbf6f58621346a5f61ab7a17d01387873" }
epoxy = "0.1.0"
libloading = "0.8.8"
euclid = "0.22"
url = "2.3"
dpi = "0.1"
rustls = { version = "0.23.12", default-features = false, features = ["aws-lc-rs"] }
async-channel = "2.5.0"
log = "0.4.0"
keyboard-types = "0.8"
prost = "0.13"

[build-dependencies]
prost-build = "0.13"

# Use a fork of epoxy that fixes the build; the upstream 0.1.0 crate blocks `cargo update`.
[patch.crates-io]
epoxy = { git = "https://github.com/theCapypara/epoxy-rs", rev = "7d9d88a8dfec2ddedc647b7a8f6c1e5b3e6c6ec0" }
